service_name: junit-visualizer
stack_name: junit-visualizer
image: avvo/junit_visualizer
facing: internal
pre-deploy: bin/pre-deploy

mysql:
  - db: junit_visualizer
    grants:
      - select
      - insert
      - update
      - delete
      - create
    as: DB
    master: true

additional_services:
  redis:
    image: redis:3.0
    service_port: 6379
    container_name: redis
  memcached:
    image: memcached
    service_port: 11211
    container_name: memcached

workers:
  - name: sidekiq
    command: bin/sidekiq

health_check: false
