service_name: junit-visualizer
stack_name: junit-visualizer
image: avvo/junit_visualizer
facing: internal
pre-deploy: bin/pre-deploy

additional_services:
  redis:
    image: redis:3.0
    service_port: 6379
    container_name: redis
  memcached:
    image: memcached
    service_port: 11211
    container_name: memcached
  mysql:
    image: mysql:5.6
    service_port: 3306
    container_name: mysql
    environment:
      MYSQL_DATABASE: junit_visualizer
      MYSQL_ROOT_PASSWORD: root

workers:
  - name: sidekiq
    command: bin/sidekiq

health_check: false
