service_name: junit-visualizer
image: avvo/junit_visualizer
facing: internal
pre-deploy: [bin/pre-deploy]

mysql:
  - db: junit_visualizer
    grants:
      - select
      - insert
      - update
      - delete
      - create
      - drop
      - index
      - alter
    as: DB
    master: true

workers:
  - name: sidekiq
    command: [bin/sidekiq]

additional_services:
  redis:
    image: redis:3.0-alpine
    service_port: 6379
    container_name: redis
  memcached:
    image: memcached
    service_port: 11211
    container_name: memcached

health_check: false

routing:
  lb_port: 8890
  path: /
  port: 3000
  protocol: http
  subdomain: junit-visualizer
