development:
  host: <%= ENV.fetch('REDIS_HOST', 'localhost') %>
  port: <%= ENV.fetch('REDIS_PORT', 6379) %>
  db: 7
test:
  host: <%= ENV.fetch('REDIS_HOST', 'localhost') %>
  port: <%= ENV.fetch('REDIS_PORT', 6379) %>
  db: 7
ec2:
  host: <%= ENV.fetch('REDIS_HOST', 'localhost') %>
  port: <%= ENV.fetch('REDIS_PORT', 6379) %>
  db: 7
stag:
  host: <%= ENV.fetch('REDIS_HOST', 'redis1stag.corp.avvo.com') %>
  port: <%= ENV.fetch('REDIS_PORT', 6379) %>
  db: 8
production:
  host: <%= ENV.fetch('REDIS_HOST', 'redis1awl') %>
  port: <%= ENV.fetch('REDIS_PORT', 6379) %>
  db: 7
